import { useState, useEffect } from 'react'
import { api } from '../lib/api'

export default function WeeklyBriefing({ property }) {
  const [briefings, setBriefings] = useState([])
  const [selected, setSelected] = useState(null)

  useEffect(() => {
    if (!property) return
    api.getBriefings(property.id).then(b => {
      setBriefings(b)
      if (b.length > 0) setSelected(b[0])
    }).catch(console.error)
  }, [property])

  if (!property) {
    return <div className="flex items-center justify-center h-96"><p className="text-gray-500">Select a property first</p></div>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="font-heading text-2xl text-amber uppercase tracking-wider">Weekly Briefings</h2>
        <span className="font-mono text-xs text-gray-500">
          Auto-generated intelligence summaries
        </span>
      </div>

      {briefings.length === 0 ? (
        <div className="card text-center py-12">
          <h3 className="font-heading text-lg text-amber mb-2">NO BRIEFINGS YET</h3>
          <p className="text-gray-500 text-sm max-w-md mx-auto">
            Weekly briefings are auto-generated each Monday morning. They summarize the past week's
            activity, identify trends, and provide recommendations for the coming week.
          </p>
          <p className="text-gray-600 text-xs mt-4 font-mono">
            Requires: Claude API key configured + at least 1 week of sighting/photo data
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Briefing List */}
          <div className="space-y-2">
            {briefings.map(b => (
              <button key={b.id}
                className={`w-full text-left card transition-colors ${
                  selected?.id === b.id ? 'border-amber/50' : 'hover:border-bark/50'
                }`}
                onClick={() => setSelected(b)}>
                <div className="font-heading text-sm text-gray-200">
                  Week of {new Date(b.weekOf || b.generatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                </div>
                <div className="flex gap-3 mt-1 text-xs font-mono text-gray-500">
                  {b.newCamHits != null && <span>{b.newCamHits} cam hits</span>}
                  {b.newSightings != null && <span>{b.newSightings} sightings</span>}
                </div>
                {b.autoGenerated && (
                  <span className="text-[10px] font-mono text-gray-600 uppercase">auto-generated</span>
                )}
              </button>
            ))}
          </div>

          {/* Selected Briefing */}
          <div className="md:col-span-2">
            {selected ? (
              <div className="card">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-heading text-lg text-amber uppercase">
                    Week of {new Date(selected.weekOf || selected.generatedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                  </h3>
                  <span className="font-mono text-xs text-gray-500">
                    Generated {new Date(selected.generatedAt).toLocaleString()}
                  </span>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-2 gap-3 mb-4">
                  <div className="bg-forest-dark rounded p-3">
                    <div className="stat-value text-lg">{selected.newCamHits ?? '-'}</div>
                    <div className="stat-label">New Cam Hits</div>
                  </div>
                  <div className="bg-forest-dark rounded p-3">
                    <div className="stat-value text-lg">{selected.newSightings ?? '-'}</div>
                    <div className="stat-label">New Sightings</div>
                  </div>
                </div>

                {/* Narrative */}
                {selected.narrative ? (
                  <div className="space-y-3">
                    {selected.narrative.split('\n').filter(Boolean).map((line, i) => (
                      <p key={i} className="text-gray-300 text-sm">{line}</p>
                    ))}
                  </div>
                ) : (
                  <p className="text-gray-500 text-sm">No narrative content available.</p>
                )}

                {selected.notableActivity && (
                  <div className="mt-4 p-3 bg-amber/10 border border-amber/20 rounded">
                    <h4 className="font-heading text-sm text-amber uppercase mb-1">Notable Activity</h4>
                    <p className="text-gray-300 text-sm">{selected.notableActivity}</p>
                  </div>
                )}

                {selected.weekOutlook && (
                  <div className="mt-4 p-3 bg-forest-dark rounded">
                    <h4 className="font-heading text-sm text-amber uppercase mb-1">Week Ahead Outlook</h4>
                    <p className="text-gray-300 text-sm">{selected.weekOutlook}</p>
                  </div>
                )}
              </div>
            ) : (
              <div className="card text-center py-12 text-gray-500 text-sm">
                Select a briefing from the list
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
